name: GitIngest on Release

on:
  release:
    types: [published]

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Show release metadata
        run: |
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Author: ${{ github.event.release.author.login }}"
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Release Body: ${{ github.event.release.body }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install GitIngest
        run: pip install gitingest==0.4.2

      - name: Run GitIngest
        run: |
          echo "⚙️ Running GitIngest..."
          gitingest --repo-url https://github.com/kagent-dev/kagent > ingest.log
          echo "GitIngest run complete."

      - name: Upload GitIngest log
        uses: actions/upload-artifact@v4
        with:
          name: gitingest-log
          path: ingest.log
